'use strict';
const state={products:[],editing:null};
const $=id=>document.getElementById(id);
const api=async(path,opts={})=>{const headers=new Headers(opts.headers||{});headers.set('Accept','application/json');if(opts.body)headers.set('Content-Type','application/json');const res=await fetch(path,{...opts,headers,credentials:'same-origin',cache:'no-store'});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||`Error ${res.status}`);return data;};
function showMessage(text,kind=''){const el=$('message');el.textContent=text;el.className=`message ${kind}`;}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function render(){const q=$('search').value.trim().toLowerCase();const rows=state.products.filter(p=>`${p.sku} ${p.modelo} ${p.color}`.toLowerCase().includes(q));$('rows').innerHTML=rows.map(p=>`<tr><td><strong>${esc(p.sku)}</strong></td><td>${esc(p.modelo)} · ${esc(p.color)} · ${esc(p.tam)} oz</td><td>$${Number(p.precio).toLocaleString('es-MX')}</td><td>${Number(p.stock??0).toLocaleString('es-MX')}</td><td><span class="status ${p.activo===false?'off':'on'}">${p.activo===false?'Oculto':'Visible'}</span></td><td><button class="btn ghost edit" type="button" data-sku="${esc(p.sku)}">Editar</button></td></tr>`).join('')||`<tr><td colspan="6">No hay resultados.</td></tr>`;}
function fill(p){$('formTitle').textContent=p?'Editar producto':'Nuevo producto';state.editing=p?.sku||null;$('sku').value=p?.sku||'';$('sku').readOnly=!!p;$('modelo').value=p?.modelo||'';$('tam').value=p?.tam||'';$('color').value=p?.color||'';$('precio').value=p?.precio??'';$('stock').value=p?.stock??0;$('descripcion').value=p?.descripcion||'';$('activo').checked=p?.activo!==false;}
function openEditor(p){fill(p);$('editor').showModal();}
async function load(){const me=await api('/api/admin/me');$('sessionStatus').textContent=`Sesión autorizada: ${me.email}`;state.products=await api('/api/admin/products');render();$('app').classList.remove('hidden');}
$('search').addEventListener('input',render);$('newProduct').addEventListener('click',()=>openEditor(null));$('rows').addEventListener('click',e=>{const btn=e.target.closest('.edit');if(!btn)return;const p=state.products.find(x=>x.sku===btn.dataset.sku);if(p)openEditor(p);});$('closeDialog').addEventListener('click',()=>$('editor').close());$('cancel').addEventListener('click',()=>$('editor').close());$('productForm').addEventListener('submit',async e=>{e.preventDefault();const payload={sku:$('sku').value.trim(),modelo:$('modelo').value.trim(),tam:Number($('tam').value),color:$('color').value.trim(),precio:Number($('precio').value),stock:Number($('stock').value),descripcion:$('descripcion').value.trim(),activo:$('activo').checked};try{showMessage('Guardando…');const saved=await api('/api/admin/products',{method:'PUT',body:JSON.stringify(payload)});const idx=state.products.findIndex(x=>x.sku===saved.sku);if(idx>=0)state.products[idx]=saved;else state.products.push(saved);state.products.sort((a,b)=>a.sku.localeCompare(b.sku));render();$('editor').close();showMessage('Producto guardado correctamente.','ok');}catch(err){showMessage(err.message,'err');}});
load().catch(err=>{$('sessionStatus').textContent='Acceso no autorizado o servicio no configurado.';showMessage(err.message,'err');});
